package ru.javawebinar.basejava.web;

import ru.javawebinar.basejava.Config;
import ru.javawebinar.basejava.model.*;
import ru.javawebinar.basejava.storage.Storage;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.Part;
import java.io.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.UUID;

import static ru.javawebinar.basejava.util.DateUtil.NOW;
import static ru.javawebinar.basejava.util.ImageUtil.getBytesFromInputStream;

@MultipartConfig
public class ResumeServlet extends HttpServlet {

    private Storage storage;

    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        storage = Config.get().getStorage();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws javax.servlet.ServletException, IOException {
        request.setCharacterEncoding("UTF-8");
        String uuid = request.getParameter("uuid");
        String fullName = request.getParameter("fullName");
        Resume resume;


        if (uuid.equals("new")) {
            resume = new Resume(UUID.randomUUID().toString(), fullName);
        } else {
            resume = (Resume) storage.get(uuid);
            resume.setFullName(fullName);
        }

        Part filePart = request.getPart("photo");
        if (filePart != null) {
            InputStream inputStream = filePart.getInputStream();
            byte[] bytesFromInputStream = getBytesFromInputStream(inputStream);
            resume.setBytes(bytesFromInputStream);
            inputStream.close();
        }

        for (ContactsType type : ContactsType.values()) {
            String value = request.getParameter(type.name());
            if (value != null && value.trim().length() != 0) {
                resume.addContact(type, value);
            } else {
                resume.getContacts().remove(type);
            }
        }
        for (SectionType typeSection : SectionType.values()) {
            switch (typeSection) {
                case PERSONAL:
                case OBJECTIVE:
                    String value1 = request.getParameter(typeSection.name());
                    if (value1 != null && value1.trim().length() != 0) {
                        resume.addCategory(typeSection, new StringCategory(value1));
                    } else {
                        resume.getSections().remove(typeSection);
                    }
                    break;
                case QUALIFICATIONS:
                case ACHIEVEMENT:
                    String[] value2 = request.getParameterValues(typeSection.name());
                    List<String> list = new ArrayList<>();
                    if (value2 != null) {
                        for (String v : value2) {
                            if (v != null && v.trim().length() != 0) {
                                list.add(v);
                            }
                        }
                    }
                    if (!list.isEmpty()) {
                        resume.addCategory(typeSection, new ListCategory(list));
                    } else {
                        resume.getSections().remove(typeSection);
                    }
                    break;
                case EDUCATION:
                case EXPERIENCE:
                    List<Organization> listOrganizations = new ArrayList<>();
                    int organizationCounter = Integer.valueOf(request.getParameter("organizationCounter"));
                    int positionCounter = Integer.valueOf(request.getParameter("positionCounter"));

                    for (int i = 0; i <= organizationCounter; i++) {
                        String organizationName = request.getParameter(typeSection.name() + "_organization" + i + "_1name");
                        if (organizationName != null) {
                            List<Organization.Position> listPositions = new ArrayList<>();
                            String organizationUrl = request.getParameter(typeSection.name() + "_organization" + i + "_2url");
                            for (int k = 0; k <= positionCounter; k++) {
                                String title = request.getParameter(typeSection.name() + "_organization" + i + "_position" + k + "_1title");
                                if (title != null) {
                                    String startDate = request.getParameter(typeSection.name() + "_organization" + i + "_position" + k + "_2startDate");
                                    String endDate = request.getParameter(typeSection.name() + "_organization" + i + "_position" + k + "_3endDate");
                                    String description = request.getParameter(typeSection.name() + "_organization" + i + "_position" + k + "_4description");

                                    if (endDate != null && endDate.trim().length() != 0) {
                                        listPositions.add(new Organization.Position(LocalDate.parse(startDate), LocalDate.parse(endDate), title, description));
                                    } else {
                                        listPositions.add(new Organization.Position(LocalDate.parse(startDate), NOW, title, description));
                                    }
                                }
                            }
                            listOrganizations.add(new Organization(new Link(organizationName, organizationUrl), listPositions));
                        }
                    }
                    if (!listOrganizations.isEmpty()) {
                        resume.addCategory(typeSection, new OrganizationsCategory(listOrganizations));
                    } else {
                        resume.getSections().remove(typeSection);
                    }
                    break;
                default:
                    break;
            }
        }

        if (uuid.equals("new")) {
            storage.save(resume);
        } else {
            storage.update(resume);
        }
        response.sendRedirect("resume");
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws javax.servlet.ServletException, IOException {
        String uuid = request.getParameter("uuid");
        String action = request.getParameter("action");
        if (action == null) {
            request.setAttribute("resumes", storage.getAllSorted());
            request.getRequestDispatcher("/WEB-INF/jsp/list.jsp").forward(request, response);
            return;
        }
        Resume resume;
        switch (action) {
            case "delete":
                storage.delete(uuid);
                response.sendRedirect("resume");
                return;
            case "view":
                resume = (Resume) storage.get(uuid);
                getImage(request, resume);
                break;
            case "edit":
                resume = (Resume) storage.get(uuid);
                break;
            case "new":
                resume = new Resume();
                break;
            case "viewnoedit":
                resume = (Resume) storage.get(uuid);
                getImage(request, resume);
                break;
            case "noedit":
                resume = (Resume) storage.get(uuid);
                break;
            default:
                throw new IllegalArgumentException("Action " + action + " is illegal");
        }
        request.setAttribute("resume", resume);
        request.getRequestDispatcher(
                ("noedit".equals(action) ? "/WEB-INF/jsp/noedit.jsp" : "view".equals(action) ? "/WEB-INF/jsp/view.jsp" : "edit".equals(action) ? "/WEB-INF/jsp/edit.jsp" :
                        "viewnoedit".equals(action) ? "/WEB-INF/jsp/viewnoedit.jsp" : "/WEB-INF/jsp/new.jsp")
        ).forward(request, response);
    }

    private void getImage(HttpServletRequest request, Resume resume) throws IOException {
        ByteArrayInputStream inputStream = new ByteArrayInputStream(resume.getBytes());
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        byte[] buffer = new byte[4096];
        int bytesRead = -1;

        while ((bytesRead = inputStream.read(buffer)) != -1) {
            outputStream.write(buffer, 0, bytesRead);
        }

        byte[] imageBytes = outputStream.toByteArray();
        String base64Image = Base64.getEncoder().encodeToString(imageBytes);
        if (base64Image == null || base64Image.length() == 0) {
            base64Image = "/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABkAAD/4QN8aHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjUtYzAyMSA3OS4xNTQ5MTEsIDIwMTMvMTAvMjktMTE6NDc6MTYgICAgICAgICI+IDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+IDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdFJlZj0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlUmVmIyIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6NzM5ZDE1NDQtMjhlOS00ZjkwLWExOTgtYWU1YWM4YjBlOTU1IiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOkJDNjUzNzdBOTkyMDExRTNCNzdEQzUzNjZBRjE4QzI0IiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOkJDNjUzNzc5OTkyMDExRTNCNzdEQzUzNjZBRjE4QzI0IiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDQyAoTWFjaW50b3NoKSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjczOWQxNTQ0LTI4ZTktNGY5MC1hMTk4LWFlNWFjOGIwZTk1NSIgc3RSZWY6ZG9jdW1lbnRJRD0ieG1wLmRpZDo3MzlkMTU0NC0yOGU5LTRmOTAtYTE5OC1hZTVhYzhiMGU5NTUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7/7gAmQWRvYmUAZMAAAAABAwAVBAMGCg0AABQoAAAilwAAM0gAAD04/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgIDAwMDAwMDAwMDAQEBAQEBAQIBAQICAgECAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwP/wgARCAJYAlgDAREAAhEBAxEB/8QA6QABAAMBAQEBAQEAAAAAAAAAAAYHCAUEAwIBCQEBAAAAAAAAAAAAAAAAAAAAABAAAQMDAwMCBAYDAAAAAAAABQIDBAABBkBQFhITFCAwETEVNRCQwCEiI2AkNBEAAgEBAgUNCQ4EBAcBAAAAAQIDBAARITFBURJAUGFxgSIyEyOk5AU1kaGxQlJyknMUIDDBYoKisjNDU2OToyTCg8PEkNGzNGBEVGSElLQVEgEAAAAAAAAAAAAAAAAAAADAEwEAAQIGAgEEAQQDAQAAAAABESExAEBQQVFhcYGRIDDwobGQwMHRYOHxEP/aAAwDAQACEQMRAAAB/wBuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyEfOcfk9p3TqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhpURXJFj8gAHcLCLWLJP2AAAAAAAAAAAAAAAAAAAAAAAAAAAAACFmdCvgAAAAASU0IWsf0AAAAAAAAAAAAAAAAAAAAAAAAAAAHzM+lEH4AAAAAAALMNQnTAAAAAAAAAAAAAAAAAAAAAAAAAAB5DKRW4AAAAAAAAJEa4JMAAAAAAAAAAAAAAAAAAAAAAAAADzGRyAAAAAAAAAAA7JsMkgAAAAAAAAAAAAAAAAAAAAAAAAP4ZYKnAAAAAAAAAABJzZR7wAAAAAAAAAAAAAAAAAAAAAAACnDMQAAAAAAAAAAALdNRgAAAAAAAAAAAAAAAAAAAAAAA5piI5wAAAAAAAAAAABr8sEAAAAAAAAAAAAAAAAAAAAAAAz4UEAAAAAAAAAAAACfGwgAAAAAAAAAAAAAAAAAAAAAAfMw0cgAAAAAAAAAAAAA2oSwAAAAAAAAAAAAAAAAAAAAAAgBj4AAAAAAAAAAAAAGgi/gAAAAAAAAAAAAAAAAAAAAACgjPgAAAAAAAAAAAAALDNegAAAAAAAAAAAAAAAAAAAAAGViqAAAAAAAAAAAAAAdc3SAAAAAAAAAAAAAAAAAAAAAAY8IEAAAAAAAAAAAAAD+m+z6AAAAAAAAAAAAAAAAAAAAAAxkQwAAAAAAAAAAAAAA3me0AAAAAAAAAAAAAAAAAAAAAGNyDgAAAAAAAAAAAAAG+D0AAAAAAAAAAAAAAAAAAAAAAyWVmAAAAAAAAAAAAAD2G9AAAAAAAAAAAAAAAAAAAAAADN5R4AAAAAAAAAAAAAJgbQAAAAAAAAAAAAAAAAAAAAAAKnMrgAAAAAAAAAAAAAug0wAAAAAAAAAAAAAAAAAAAAAAcwwufIAAAAAAAAAAAAA1mWaAAAAAAAAAAAAAAAAAAAAAADKZVYAAAAAAAAAAAAOybhPsAAAAAAAAAAAAAAAAAAAAAACFGNT+AAAAAAAAAAAAGjC9AAAAAAAAAAAAAAAAAAAAAAAAZdKhAAAAAAAAAAABJjaR6AAAAAAAAAAAAAAAAAAAAAAAAc4xecAAAAAAAAAAAH2NhE4AAAAAAAAAAAAAAAAAAAAAAAABEDHh4QAAAAAAAAAf006XEAAAAAAAAAAAAAAAAAAAAAAAAACCmSTngAAAAAAAA/RpEu0AAAAAAAAAAAAAAAAAAAAAAAAAAEUMoEZAAAAAAAB7TUBaYAAAAAAAAAAAAAAAAAAAAAAPiVsV0RI5B1jQZPwDxmeilD5gAAAAAFkmlSRAEeM7kNOmSYn5aJ0gAAAAAAAAAAAAAAAAD5lKFDHHAAP6XKaKOgARwpAqU5YAAAPQWaXcT0A/BSJns8gAB6S5TQB0gAAAAAAAAAAAAAAAcYyiQYAAAA7RpUtEAH4IaQsjpzj8HuO8S8nR6gARIzGQgAAAA7RqwnQAAAAAAAAAAAAAAOQY7I0AAAAACxy/ydAAAAAAAj5RBTZ8gAAAAD1GuieAAAAAAAAAAAAAA+Zj8gYAAAAAABMi3S0CQgAAA5xWhUpXB+AAAAAAAdQ2ed0AAAAAAAAAAAAAoUzyAAAAAAAAASEmRIjon6PEcEiJEz8AAAAAAAAAsY10AAAAAAAAAAAADimIzygAAAAAAAAAAAAAAAAAAAAAAGsC0AAAAAAAAAAAADNpSIAAAAAAAAAAAAAAAAAAAAAAAJebQP6AAAAAAAAAAAeAwyeQAAAAAAAAAAAAAAAAAAAAAAAA16WGAAAAAAAAAAAU2ZjAAAAAAAAAAAAAAAAAAAAAAAABbhqQAAAAAAAAAAAyUVoAAAAAAAAAAAAAAAAAAAAAAAADoG6z6gAAAAAAAAAHwMIHlAAAAAAAAAAAAAAAAAAAAAAAAANhk9AAAAAAAAAAIGY7AAAAAAAAAAAAAAAAAAAAAAAAABoQvwAAAAAAAAAAo0ziAAAAAAAAAAAAAAAAAAAAAAAAACzjWQAAAAAAAAABl4qAAAAAAAAAAAAAAAAAAAAAAAAAAHfNwgAAAAAAAAAGNSEgAAAAAAAAAAAAAAAAAAAAAAAAA/pvQ9YAAAAAAAAAMJHMAAAAAAAAAAAAAAAAAAAAAAAAAANpktAAAAAAAAAPMYIAAAAAAAAAAAAAAAAAAAAAAAAAABrcskAAAAAAAAA4Jh0AAAAAAAAAAAAAAAAAAAAAAAAAAGoi3gAAAAAAAACImLQAAAAAAAAAAAAAAAAAAAAAAAAAAaSLuAAAAAAAAAIOY3AAAAAAAAAAAAAAAAAAAAAAAAAABogvgAAAAAAAAAgJj0AAAAAAAAAAAAAAAAAAAAAAAAAAGgi/gAAAAAAAACvzH4AAAAAAAAAAAAAAAAAAAAAAAAAANAGgAAAAAAAAACFGNAAAAAAAAAAAAAAAAAAAAAAAAAAAaLL1AAAAAAAAAOQYWAAAAAAAAAAAAAAAAAAAAAAAAAABqktcAAAAAAAAAGHTggAAAAAAAAAAAAAAAAAAAAAAAAAG3iRAAAAAAAAAAzYUkAAAAAAAAAAAAAAAAAAAAAAAAACWm0wAAAAAAAAACMmKT5gAAAAAAAAAAAAAAAAAAAAAAAAGny4QAAAAAAAAAAZ6KEAAAAAAAAAAAAAAAAAAAAAAAABPTYB+wAAAAAAAAAAfMyoVcAAAAAAAAAAAAAAAAAAAAAAACSmwzsAAAAAAAAAAAA+ZnYo4/IAAAAAAAAAAAAAAAAAAAAABYxqU6oAAAAAAAAAAAABDChysT4AAAAAAAAAAAAAAAAAAAA/pOy8S0j+gAAAAAAAAAAAAAA8ZCSMHMPmAAAAAAAAAAAAAAAAD9HuJETc64AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABBQL8i9x9hmlnA7dXyYHauUAr0nIAy6amw3/8DnHxY+pebSFVIOFpVXve9/THJEItRcyJNVBysVLq17KtvhQ7AFWJZKRIe7ALzxqhWVw5u9KUlCTWWqVSlKVf3w2SyhtRJkeczuz77UZo7kLxVWiGk5Qt8WVjFY+6POtsNHTjpZ7SQJ8gdIFk2Csbc8mOfUHtMJKPCpcaSzLY3HLDHiMajFTHhydwmSm4UaXKdmydTjZT6kP2/NCH76rGyH08ntylJQmfLVOm6sJN88ZtuTSvFD6zCJX7bbnD/wDHWYs/2DW25i71ltYPd7M7bcnV1HNZ8qTfqTtmQ/etbG/59syS3Sb1rVulrbMtb6DWsjt91/bc3Z+ErWAGe+Y23MY3eFazCo3XO22ZHTLiLQpterxOH4wnbstgeKS1Q+GufMQhLSNuPjfqY75arDRnQ3uGWCfElagSNcKTWm0Mt7hLiszY5Mc8Ml6ZttbqwQhImJuRkQyXjSYz0R7S4yA8JO6GwbJdmVFfhvaK1r3vjmN+Nu5URFLMkxMsU7oI8Z+W6Cxpkbt7jjbSZeWiY1SM2mKpzKDblKNl1VDyUtEWKyKCU9D8dmU0Ww91qloW2r3RWMTiFDxcMY1+JApDGNkctnyr2MlrU3khtumMzJt1FzMe7UaZFmI2NSkoSUzFlmphCZPX6flQjLX41RpUeY1+M8TAJJnYXJbqTBlw1ew006+qDiJKTQ7HBo70KVZNi+XttU++9Jc9LTzrCxmYvtVFlxprWwTp8YdHLnpZZfswSEsc6IyiIQ9KkpVaRjweTT2EwVUvB37VfCSVcKJ0nCJVNYPHtUfFgzFNMMsJ9BM1BFIKnppW/swSEoc8FOxy7eunTWB8YoUkFZPuDMnID6H5EMIe/NKQBySWYyH6WtbivbZedjOgjbZdjWKUlCTxlZaV78E+UgVDzWOuopUdN9mRLixbTMxGsVNyorLpSlKv70OY/Akjp7JKJq8wL9NtHHLEotM5gYbpGcP2q2ct1zhql5yunczKLp88Yk0pSlX0WNl/ps3VEJrY+G+85Je2/FifnQNTmZHuSNwBkPppHUSpCIseQ8uS/uOMTvNFafM5nZg7lh0zsEdPlkvyS+5RX1RZKFpcRpXHEtNvuqfe3PGpPkhtLksjxw26YPI/hpc3f+EbdMRf7RjS5o91k90FPeOS0uRu941unyphzvMaSa53pm6gnO6H0by+2zu2Jr6gmjKK6Bm7YWr4itGev0h92wi/+no8kv8AAJu2D3/q0eT/AGLdsG+Wjyj7Fu2C6TIk9YXdsHT/AEaOe15EHdsOa7YnSFI3hkN1ExvDG6TNIXbk7oDheeT0peAklAWhTatzxAb40TTZcGvZW5AA6isu1rJtplJStOQ4+sa5uAsXJKyIMFgdG1CkpWk1ia273tdN9tD45LJ3hwo0BjVkgQ8pU/ESUWnGnGVbR86hY2Vm0NxSBC2B5hiQl/Fwr9OYTAvV8GTXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LXBa4LVsGtSMIiWpnEQzVR4EKJ+Q//AP/aAAgBAgABBQL9L8//2gAIAQMAAQUC/S/P/9oACAECAgY/Ai/P/9oACAEDAgY/Ai/P/9oACAEBAQY/Av8AAvvmmiiGeSRE+kRbfdY0p8yQSf6elb/fruQVJ8EJt/vh/wCvVjwwWwdYQfKLR/TVbchV003qp43+ix/4DKzVAeUfYQcrLfmNx0EPnEWK0VLHCPvJyZX2wi6CKfSseNrp7j4sbcSm1ow6ANrySScpwn3Q9nrKiMDxRK2h+WSUPcsBUxw1a5TdxEvpRji/mWCyO1HIfFqMEd+xML0u87RsGUhlIvBBvBGcEYxr6Vlfjai7e00Vxk2C+SJdvcsyB/Zac/YwEi8fiS4HfvLse+30s7BL8MD7+BtuM4ATnFxssVVdR1Bwb4/t5D8WQ8AnM3dOvRd2CqoLMzEBVAxkk4ABZ6bqo6K8F6zxmz+zg8EfGOHNnsWYlmY3szG8knGSThJOoFhn0qmjxcWTykI/BY5B5JwbVlqKWQSxtlGNTlV1xo4zHXd553WOKMaTu2ID4Scgy2MMWlDQqd7H4012J5ru8uIajE1M2A3cbE31cy+S48Bxi3HQG5hcJoWO/hbMc6nIcuurzTOI4o1LO7YlAtorpR0UR5GLyji42XO5+aNSpU0zaLrwlPAkTLHIMqmy1EOA8GaInfwyZVOcHIco109jpn/ZQNhYYqmUeNsxJ4ufHm1OtRHvkO9nivwSx5RsMPFOQ2iqYG04pV0lPhBzMpwEZ9cv/wA+na6oqV5Zhjipzgu2Gmxebuap9hnb9rVNvCcUNQcCnYWXEdm7Z1xmqpfq4ULnOx8VB8Z2wC01VMb5JnLnMPJUfFRcA2NVLxhvqaa6GfO2Dk5f5ij0gdcIOrY2xXVFRdnxQodrC3c1XFpNdBU/t5s1znk3PmSXbl+t7OxuVQWY5lAvJ3Bapq2+2lZgD4qYo1+RGANWUs5N8mhxU2fjYt4xPn3aW7rdU3G559GmT+b9Z+iG1bW0RPkVMY/Sl/g1uoKUZTLOw80LHH9JtW0w8WcSwN8pCy/qINbgn3NLCm6xkl8D6to5vu6qB9xZVJ72t1dsGBfRpoR4dW32VvKUHui/W3rD139NNXQepi+gNba8fiRn0oIm+HV0a+TGg7iga2zN97DTydyMRf09WwRfeTRx+m4X4dbqKo+8geH8mTT/AK+rer08mcTH+QDN/T1uEwGGlnRz6uS+JvnMvc1bU1RxU8GgPWTtg+ZG3d1uqKVsU8Lx35iy71vkths8bjReNmR1zMpuYbhGrEkYXPVu1Qc+hwIhtFF0vla3+0KOSrhxuwJluWYbuBvlarp6RPtpAGPkxjfSP8hATZI0GikaqiLmVRoqNwDW+WJRfPFy1Pn4xAd5/NXBt2uOqpOs5V3018NNf90Dykg89xdubOuPt8K/t6tjxl2KKpxtuTcLbv1THTLeE4c8g+zhXhN5xxDZNkiiUJHEioijEqqLgO5rjLSzrpRSronOMzLmZDhGzZ6WbJvo5PFliPBdfhzHU6RxqXkkYIiLhLMxuAG2bBDcaqa56lx5XixKfIiv3Th1z4prknjvanm8h8xzxvdhtJT1CGOWM3Mp7xByqwxHLqYV1Yn7xxyUbf8ALRsMv4zjHmGDPrrkjq4xyM/f4uXPGT6PhenqYzFKhwqe8ynEynIdRgAEkm4AYSScQAz2Sv6wT9xwoKc/YZpJPxsw8Xbxa7aEw0ZV+pqFHKRn+JDlW3F1Kbw/VTrhilHxTkbODh1CsFPE0sr8FFHfORVGUnALLU1OjPW5MsdPsR38J/jdzW8ySukaLwndgijbZrgLFY2kq3H3C8nf619FSPN0rH2akghGeVnmbvcSveNv95oDNHDCvf4vT79sPWNX8mZ1+iRa81LVSeNFVEyg7Tk8Ym4bCO/2eq/6eUjfH8F8Al7zbHuGhqI0lifhI4vG3sEZ8Ys03VhM0eM0znlk9WxwSjY4W3YpIrI6m5kcFWU5ipwg+/LJKDSUpw8ZKvKOPwosBN+c3DbtxdLHcT9ZK2+mlOd3+AYPccZVShb+BEu+mk8xMe7isUpP2UGTQwzt50t28+Tdtm3aVbu1Ep8LG2CvkPrEhk+nG1uWipqgZd60T91G0Pm2AqoZqQ+V9fEN1AsnzLadLPFOuXi3DaPnDhKdvWQu7BEUXszEKqgYyScAAs0PVqCofF7RJeIB5i4Gl7w27adXUSTHICbkXzIxcibg91eMBFlg6x0qmDEJ8dRGPjX/AFy/O27LPTSpNE2JkPeYY1YZjh9xdVQKzXXLKu8mXakXDdsG8WL0E61C5Ipro5toP9U59C2jVU00B+OhCnzX4Dbh95EcMckrnEkaM7H5Kgmwao0KKP8AE3812xEh+kVsHEftE4+3qLnIOeNOBH4dn3BZiFVReWY3AAYyScAAs0HVd00mI1TDkU9Uv2p2eDt2aaeR5ZX4Tubyf8gPdCSCR4pFxPGxRhurcbLF1knHx4vaIwFmXZdMCSfNO3YT0sqzRnKuQ+SynfI2wdYWqKp9FBgUY3kbIka+MxsVY8TSg8nTKcGw0p+0fvDJ71x1JKYz4y445B5MiHAw8FlhqNGkqzg0WPIyn8KQ4ifJOHb9yVYBlOMMLwdsGxL0UaMfGg0oN26Iqh3RbkKqpi8/i5gO4sR79uT6wibz4Hj8DyW3tTQnbecf27Ww1FB+ZUH+2Ft/XU6+bHI/h4u3L180nqokh77tPYH2dp2HjVEjP3UXQiPctoQRRwp5MSLGvcUAe55eTSmIvSmjuMrZrx4i7JsVduJpr97TRk6GwZGxytt4Mw96E9LKUbxlxxyL5MiYmFrsEVWg5WnJ/UiPjx98avkqqhtFEyeM7eLGgyu1jPMblF4hhB3kKZhnY5Tl99WNz7XTDBxUzHTQZopsLLtG8WCrNxEx+wqLo2vzI1+hJuG/3++rqEjOSIb6ZvNiW993FZourk9ljxcc9zVBHxRhSL5x2bM8jM7sb2dyWZjnLHCT74k8DtHLG2kjrjB+EHv231yVkQHHxZ/xY/w2+adWs7sFRFLMzYAqqLyScgAtvSRSQkrTpivzzOPLk7w1ABDUs8Q+xn5WO7MNLfIPNIsFrqZ4TlkgPGx7ZRtF1HpWHs1ZDIT4mloS/lSaMne950qmohgH4sipftAm9rEUyy1j5wOJi3XkGn3FNisci0cZ8WnwPdszG+S/zdGxZiWY4SzG8k5yThPv8dVTtoyRn5LL4yOMqOLR1UOJ8Dp40Ug4cbbI74w6sHVUDYWAerIyLjjh+VwjsXZ9SDiK6oQDEnGF4/y30k71t+aao9bDcf0GhFuU6vifzJ3j+lHLbD1a42qoH+gtsHV0n/sKP6RtvOrVHn1RbvCBLcnHSQ7Ijd27ryFe9blK+cDNERANrkRHfYsxLMcZY3k7ZOowkrXUlUQk1+KNvs5tjRJw/F1XPVyYok3q+XIcEaDznNpZ5W0pJnaRz8ZjfuDXDiJGvqKLRja/G8P2L7OAaJ2tnVUXV0Z3lPdLPszON4p9XGfna4wzk3QseJqPUyEXn+Wbm3NUzVMnAgieRtnRF9w2WxWlqJTfJNI8j7bm/BsDXKIMb5aX9tJnIQDim3YiN0aoio1O+q5L39TBcx7spXua5tSsd5WRkD10N7p8zSGqJEBvSkRKcecN/Ju6b3bmudPUrwoJo5Rs6DA3bossiG9XVXU51YXg7o1NJK+BI0aRj8VAWPeFpZ34c0ryt50jFj3zrpSEm9oQaZtjiTcn6WjqasI4UqrTrs8cwV/0r9da6lORoqhB5wMcn0F1NRU33k0kx/kpoD/W11jTJUQzQ9xeOHfi1NFFkhpU9OR3Y/N0ddaGbIlVDpeYXCv8w6mr28mRYvyY0jPfXXW8ZLQzfexRyemgb4dS1cv3tTPJ6crN8Ou3VzZqZI/yeS/g1JLJ5Ebv6Kk/BrvTj7uSoT9ZpP49SdYNmoqq7b4h7u/rvMvkVsncMNOfDqTrE/8AbOPS3vw671q5qlT6UQH8OpK/1aDuzRDXfrEZpKc91Zf8tSV21T//AFQa79Z7dH/dakrv/G/+uDXfrT/wv7vUnWA/CDflyI/8Ou9e/lSwL6COf6mpKyDLLSzxjbaJgvf13L/f1Usg2lCQ+GM6lrKa64RzyaHq2OnF3Y2Gu1FTkXMkCaYzSPykv6jHUsFeo3tQnEyn8WLgk7LxfR11pYbr4w/HTZuKi3zA7Dne7upp6XBpkacLHxZkwxnYBxHYNmRwVdGKMpxqym4g7IOujV0q3S1l3F341pl4P5rYdq7U561pl3rXCsRRwTiWo2mxNs4c+uY0wRSQEPUP5XkwqfKk7wsFUAKAAAMAAGIAZANTsjgMrAqysLwynAQRlBFjU0yl6BztmmY+I/4ZPBbcOzrgIYBcouM0xG8hTOc7HIMtkpadbkTGTwpHPCkc5WbVLI6h0YFWVherKcBBBwEGzVPVYMkeN6THInqD9ovxeFt2IIIINxBwEEYwRkOtyyyX01Hj45hvpRmgU8K/yuDt4rLT0sYjjX0nbK7tjZzqwtNHxc+SohuWXY08GjINuxam0a2L8PeTAbMLHD8ktYpLG8TjGkisjDbVgDrTcMJOSwIpzTxH7WpviF2cIRxrbgusslR+9nGHlFugU/Fhw6Xyr9YNCeGKZfJljWQdxgbX+y8SxywSSJ8y9ox3LclV1aefxUngSO296yYbdID/AHC27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul27U5l0u3anMul2w9Znco7v7o25StqG8xI4/Dxlt9HNUeunbwQ8SLftqWCH4yRqHO292mf8B//2gAIAQEDAT8h/oXm9HJ+TYciA/8AVjxd/wADqbBYe7+A4io8/wDcUmIsQbCfw6f+BszPiIQuZdLDZsRFk5HolGGeXqe5EbzOESglRR5Vqv1cKcd9/aWDoHuTPER8sUH2IRO3HtgPiIc9UkBDXboAIqipmZzWljhNGYD19rzLlT7otUtM5Mj/AGi4XHDBlTS2mcBsJrRiPCJSuACq4YVCUkbAF+2bCiR/Bg+lMoXXIKOHFStZfY3uu7HVxoiipea1PWrp7ehAP2igSpgrjcpSwyq1Dz8g1ydlqFKV3NzZ6N8BqfiTTZilY6DhENUXZJkFVXl4Cq0MVehnYSmEMDsWSCsrlLHESFSRKU/kakIOEpjgIwJgxurfZIam6bo2pwtLigsvVlpNYVOn1drv9AokzHPfge0uwEakoSRU3BTOV0Dysy5QQjbBJdkcUlDUSXwOSAKSaSTucdRIy2l2AdDNckXG3V77h31AK0IJK6mG4SHbzapmhOwQEqhWLs+WnmCf2zSugxMDN5kv5wRnGv8AEbl89D4admcB7U4GdU1hPlYX9achQ/bwM6zgx6Kz7061spGcJHyjnanRP+BHpGnSzYnqR/RzoqBRER7LYM2wfgv8tNc+AfAGeUq3W+dN1W39Ej9Z66V0fP8AgNN/3BGdDuZStOJTujz3AnuM6p5JwyK/1OnEkZ+3IF87OoISV+KgPRNORqkjbweSIdmG7ohd9vcDOXLGHT6QtPM0doQ/Ymny5tI8IKT+RItg64qWPD1C0+AOq90wXhXjIdsIpBEURIRKIjZM00cBAVP0pbeHtqJ7goCoEnghH+rM1l3AXhekqHOW04s/AOMbwNRkJWNJLuRhRNhgNZtRCj70QNhMuDeEIQGLqYLm+Cs7AkHI7o1NDZC6sEx1hg+EqGP2db7ZqwFBXKgqAKrAFVWwG64u+OJWAUbL7cx1VNKrIqJWir75Mm5hBwsW5sFDqEiZMEzgFBAFVOKMGkUTeGz/AJHV6nvWClbbTrlHaGHFShWCidNA2Q8QuQY10ST2jG4AC7iwkywqiog7WdQqunA5aQr5YLzhihtHzC9xgVFqgP2TB84GW622eJsFQH+LBcFmVoO71ai1HkcEFPKzW9RF1HgV+gpqQAnA3dYQlsJ1ZlILpGLso8uEOqMluKA4fvJwqSnl9EtTajZiLchRAcIkm0B2D6JK0LESbGiJuoO6YfyskgflLl4KLYKufgtCYgfEyPTMwoG9S74ivlh1S3EcyfiKxYFMkpWDfCA6I+iRcKVwBdcIBGUSNt9HL1wxU0C159FeD6hUIoERhEqIlRHFOgg3DVoC7jtZjcJgkO7InqgD6IA36EaZh/gcMVoqhGwfYYYrYCB9UyPaH2f002JlGKuHVXNypj0rDT8NID8EibIJ+gn+Bg9KQAuuIvVs8SzPEOz+HCv0lfjEtlYIAt9X6vufTQOFLFQVcCOdexim5uesUsIGagOgklpTC4soMPwFVAXDAJdOcNDj39Aqv2R6bG1f4WdiOLEUHBvJ3tQP0gZzAhuAImH9xwUe1nkxJK7sfFED5WLZe2I5bB+WGA214/kYn+4/7qxF90euP4DEuf7oYexjFjOrPpwwa0Jy6SH6ziWmL/JWYZoR+aDY+1Q5IahO+/llxGuIKhbISUFEKN92jsuehxughfMkk0oe2AXFbV2FLS3QFOXwAH3CaPRAHgECgBlgxE1CJErcKZsdgPvuItlnVqAeQDdwUik+nJrz+QGEauctuqq5fuHZchAv0CiMgYaYisNjYNoayrcvQdlzj9MeFBdQCVwxW9cw26gocZeV+/QcUJ422sZ2yeVQ38UwvB2wpmp9k1HmSSXhzdAuIR1MKlNv0tYruEQr7J4dl4YRvqoeugo/frCDhmVQRLSnxWHDrwEpmD2FVo7hY5xIzd+qxS2af4RZSHXKDPGHAhzDLfsPWIya3/UEDG4jf+TcDvjz/ExIK3sg/ib4lgzYV9txnBBeNuRGeZwjOJUdyhVybVkTL+OlE7lrBm4k1TJD7tEOiu2FjOnupQbEwFgpqEdCSlWCLNUL2Tc0sSkJp+3j89dRd4gjZAfmEMREEREkSojZHjMJ7vFCHHdEO3EsiltNZwkgNjUqtbrNRE3Yid0zFFiPHRnil8y1OiwdNoH8V8pTMWDhNoF44O9TzswAclfRQ9OCEHnYI3SZZkOipJ9YPK4Lqhb+uB6f5rLSYjwgd8tVyLfuC/rLMVNsdBJ0r+NVqbC7iQ99E85aC27HHy/qtUaJN/66uWqBIJ1Cj36qKhEUIlxKidmDAsL4Lyqqs1DnViV5n+Qfr/wvV2v9U5OUWM6L9XEnjZnhP7OU7U/R6uz5QWGQ/i3+dX/KkHKXHhPktXdPs+T/AEylf4qPq9i/Ef8AbKKKTHrrvo1c5HpK9pnrKHGJFd6bdjNXdUvTk9HRlctEGHmntNWeVLcTg9ZVPZuCwUt5EHWq3djXCc4kB5ZarIbdJ0jce6wF9VYaHbAh1R44cIqkrk+aXl5UPQQkDq4Ybkale5JQCZ5TK9reJOgp4GgCgChlzA/IEq6RCExsrJy9o9VRCfJDqKu15yx66Zjq+AUilaYTEQQTjwFCADMnymcRg5Aajh95ma7lUZ7VG3Bwzh1BCEIOnGhNF258kKOxhWSgxVACVlqvggAzhlBYskRcCjaoWTCEZSj+6R6U8Y/VWsWB0kFAKAASq2AKq4bjA3W3QKWfKw9ZwJclKUcrmBgIoUCgG2f/APENqrhRk2FTwsVlOhIZ8uMP/EnjQ4zMzMzMzMzMzMzMzMzMzMzM90vD/LBbN3x3BLxwPkU/jF/+I/Hmar/Qf//aAAgBAgMBPyH+1+f/2gAIAQMDAT8h/tfn/9oADAMBAAIRAxEAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAACCAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAACCQQACQAAAAAASACCCSAAAAAAAAAAAAAAAAAASAAACAASAAAAQAAAAAASAAAAAAAAAAAAAAAAAAAAAASAAAACQAAAAAAAAAAAAAAAAAAAAAAAACAAAAAACQAAAAAAAQAAAAACAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAACQAAAAAAAAAAAAAQAAAAAAAAAQCQAAAAAAAAAACAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAACCAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAASQAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/9oACAEBAwE/EP6F9J5TRvmmsKE10fTiS9OHEYk2unCz1fDAClim2mqEO8MhGyK9j+0YVgNlOu0T6RI/8DYINgACD5TEmmuyEfkHVSKBIS27DnOKbqtcPMYrFddRyv1LCHrHbREOExEmChkvPTl5ScIVAgSuBDyN4wc6S0YrKUiKJrrk1DY1kaqGQrIcYeGcocEWSsE8X92vgDZRnvwNFY42B2/qEkRJGSYIIgiIkiVEbI7jrKeOlpnUaUABLhyzb0qSG1BuRcBGLYbTQNVCqy5BODbbzsyEpENqhu3EsHAfAIABElC6tTqpHYAAL8BFAoFZptc/NACAVeFTBkmiiShyhiktA6yhDEoa5bIdxQgzqq1XXteZVVLAVAKhhkm6SYNNWu1iWV6F0zCcEgo3BDiJ64BsmDbAAqoBqYUBVACVaAF1dgwoyQNyJIgt3QUzl1gW2UrORc2LIVnFKCdVgKzVVhVYqmpUiLpvjJLwN2YHMykHLWPRI451EE6hD7NgAO2FjRPEa1IKrivkfmoJmRipRKibYUk8q4ZRyqcNFDAjUHKBHuHKGi3I7wM2pQS1y4L+NRC7T0c7LDJezK9GItL8SAJZZA/WcxF8ISkvMUxwacs10pibhZGVpG5nVoa3NYIY2BGm7pyURnqzB+8hdRnUkmzMSd3xunMPLiOBKbDXgM6h0LWYNmyuDyOnRcqE9InSzy51yUZLiCjsTG2KlaAR600i2/GtYk3DPIahAMUUpSl3TTAh9iH7DPG9ANaFhHnTTRsRDwnT3H1nWFJFDdPPenEIcCykYlskibh1nWldIEic7JAVusb6dGITyQR9wX3Yzp5hbCkHZFaBsNOooGiQ7SGs6Bg0FUwazs8uzONSFygKqRX3C09TESwMSl3pbrFs3WJvsmQURoxuw3xSETiajsYOjTzmAzBsBFg1Albh6DnlyACghGo5pGYliExmYgUQu6moSpkI+JGIUGtBoRcxNbIcSFyJEFEkLgI0iY3H5CktW7XURU0Lk4PiNOwWtsJpml5HlKEVJVysS5ZIiS6uJhAYp0s8ELc0QtQQRqUVoVbT5t4HYWM/NZXoEvBlaBRyoJnDKCAJUMAXxTchkVCeZySq7AaqGDP61EEV4ogtTzjIdlSTrUR6Tqw5M+APzhCqgAFVxKiBOTEpmGzZvTDV4lz9jVr0X67iMU7R9emlRfhXcKyIqftiwifC2aoAFcAIaUl3EIWCEKI08/5SBrnCSMMvRjQDZ5TaH7hIukc2zO94AWrfFaNtKz/1zwnJnh/gHxg28WaBREFMgLEIjEWICkhNEmGkAKkS/wDtCu+77iK2aAKEHE0tkuuQi8yTACScUVNAcVjlwE+9JqKJXWpOgyNUCUaK6QGiXCSJ61TP/wB2vjwFacILaldhsUwH1QOSgBhlBXDAqnG05SezCCBEUIN0jXpHvBDakKO4tLijCCD2BX0tYb4i1xJiMyoz9a0RTceCxO8lABfDSLPJyk15MNIDKxAW712kPEMNRvP1PZA8uEwASJUcQLno2AIAbzElpGJ4l2BgioY56h9FzfTDJhMWkmG7wIquyyGHO8JhNOF+5NbInZV/s8pFWQN4zsYSpxBIcFLcJw4hVMiskJqxqor6E4sosFQBUABXEIEmqsMFPlglBBKSU057ZWKAYYAAH1Pl6ajgpQQqTCXMV4MVn6hOiWKSrQxdJ+tKBDIR8RSE0G5MYwh8jIJBJkb2HlhGGUCIHuvtBgfGeUqSkVQUJlrGD20LdUBaFjckF5fpRKh7O6RuETE6YmcW8kaystq1xVRpHktnc9rvCTcEkHiQx8uEHhSm2uIfLh7Q+XvgP7w+Re5k8EHyMMICi8d+AJ+G2EoMEDsdrG8uAcfIGIQXcHX0igVROlnPbrA00oK8D6EyiIDAEmS/aKF6yYFYGyxMO0QExiG0NQgoUSgYc/6EJY89lmUgAKCFLqDjqJAdHBbfdWiQSkyggGAFUXWA5dymuljkk2E2X37QE4xLSzpITQK4ngGEuoqJQjCNEcOV2jLL1u6K/criVf7NxYoyoFIoYNBCYalOpKZkc73dKJeORPQwBOKypzgZrDSqFAcgpcIAhwQNPFsQJYwssKkHfxRQS+uqwSCWk0z9lXOdhMmjIpAobGAjYFrdyJZULNpOgGHUmg5GoDgjs7NMpgrqq/fiXuZF0YAZwwygBN8UqSEcUMwEKIM5ScN6smqYIaNOocoVDfQJtLCnwwMEIBybsidqOsFcoDW0yH5OGBWhAoN4WX0YNNjpfuGjO/1hcVl4TKn6+eCXfNZ3mDPHAk+4m3uJDSFIvOJEKuyukblVybJwPcIosSDoKgjBEEZGolRGyOalMYsoDVxTQZlUWKZYkry5FwdGCgag7tOMKTKTjVQaRmlmEwrNgEy+9BJGo1d4mxR5cNXWFlwCYiAAkCRQ0cxAsAoIemiEO5G+LuhVovFZ0VQAKGpPWLGQqZpI3M/MzmHqWLVUBDMgTQDWsak822KJNVYSkXG4HL3GU6usRRyXYcGp14yRHG8LpNFBx8HkgG+NPOW91U614Kpwm8q0sqjNUk1SlAXmZM1vPzWWeDZ0xCd73PcaqtBZ0uwjtQ9zllribtaezcxN3rqruRJrCnCaSHcmG+WqvmT3jcEPw1V0pxmihUyRA8Vy0aIdzTeYise11V7DHIkIFRCTECtNLUAikRlfdL6YEvs1ZMki6s8P9HrKVRCttipvRgs1arVXfVlZZ9GIMpZ5LrqHzRq6JJR3HzVlPVCP5dnshq9VaQ/FS9/wyiGMTO6ULNyOrsyKBHC8+4fGUZJf4C36dXbgAvIH9DKBEcL0t+jVx0FPwTlE6BH/APZwvrV7KzeXpAHzlHBkATKAcyOzV3LiklsC399XKo5PuQzIe3zLVmNr+QrN8H3lWMEWKm4QJ8vvVGLS7J3IwLvD5yxrg6LLrFZNQWjwhWtjGfVuGyapDUAgMQSF33Cl8uoVlsECVgUblOpwQlYrIYhkRCJzkOAKVmkz0IgAAIMuHE+jNWrECIw4mlTKOIvVAjcTUZWMt0PCggIOCOFprdQhVHhisAAhGYdLJXSujwBEYcOJyNPVxGJhGiOcYJfJicJRNEQRIdOW/wBGBUQ4wUhKqKFxmu2h6iNkAADNvGa9kASHgQcRNnAwU8AFZTdkuhDCd0h85SKlRuGkv5A0+AIoMAVXD48TbAlS4orhM4naWHbqSqmzSCeAAAAAAAQAFADPr1eaTzdDrS4TgpX564eOjhFSFQsOxODYWe3CFFrArO1TPxoaIiIiIiIiIiIiIiIiIiIiIiDSJmognAjHuMKFXEFE3BjH04dgpRLUs1E3EVxGCAFyDCIoJIpXf0H/AP/aAAgBAgMBPxD+1+f/2gAIAQMDAT8Q/tfn/9k=";
        }

        inputStream.close();
        outputStream.close();
        request.setAttribute("imageFile", base64Image);
    }
}